# version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: tanki_enjoyer
      POSTGRES_PASSWORD: rock
      POSTGRES_DB: game_stats
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tanki_enjoyer -d game_stats"]
      interval: 5s
      timeout: 5s
      retries: 5

  fetcher:
    build:
      context: .
      dockerfile: Dockerfile.fetcher
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://tanki_enjoyer:rock@postgres:5432/game_stats"
    profiles:
      - fetcher_only
      - full_stack

  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://tanki_enjoyer:rock@postgres:5432/game_stats"
    profiles:
      - full_stack

volumes:
  pg_data:
