# Dockerfile для fetcher
FROM golang:1.21 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . . 
RUN go build -o fetcher cmd/fetcher/fetcher.go

# Финальный образ
FROM debian:bookworm-slim
WORKDIR /root/
COPY --from=builder /app/fetcher .
CMD ["./fetcher"]
