# Dockerfile для main
FROM golang:1.23.1 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . . 
RUN go build -o main cmd/app/main.go

# Финальный образ
FROM debian:bookworm-slim
WORKDIR /root/
COPY --from=builder /app/main .
CMD ["./main"]
